Allow: cadvisor download url override, runtime options and version bump
ome/ansible-role-cadvisor pull request #4
Opened 2019-02-19 17:29 UTC by joeweoj

Changes:

* Ability to override the cadvisor download url (still defaults to github with old format)
* Bumped default cadvisor version from v0.29.0 to [v0.32.0](https://github.com/google/cadvisor/releases/tag/v0.32.0)
* Added ability to pass [runtime options](https://github.com/google/cadvisor/blob/master/docs/runtime_options.md) to cadviser on service start 

e.g. 
```
  include_role:
    name: ansible-role-cadvisor
  vars:
    cadvisor_port: "10002"
    cadvisor_url: ""https://example.com/my-copy-of-cadvisor"
    cadvisor_version: "v0.32.0"
    cadvisor_runtime_options: >
      --enable_load_reader=true
      --disable_metrics=tcp,udp,sched
      --storage_duration=2m0s
      --prometheus_endpoint="/metrics"

```

2019-02-19 19:06 UTC, joshmoore requested changes
Thanks for the updates, @joeweoj. The change in the semantics here would break end users. Can you change this to introduce a new variable like
```
cadvisor_download := {{ cadvisor_url }}/{{ cadvisor_version }}/cadvisor
```
to remain backwards compatible?

2019-02-19 22:20 UTC, joeweoj commented
have added `cadvisor_download` variable (and fixed tests).

if you're happy with the change, would you like me to squash the commits into a single commit?

2019-02-20 06:17 UTC, joshmoore approved these changes

2019-02-20 06:18 UTC, joshmoore commented
Thanks @joeweoj. Changes look good. @manics: can sign off on the bumped version?

2019-02-20 11:17 UTC, manics approved these changes
Thanks!

2019-02-20 11:45 UTC, merged